version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build:
      context: ./  
    depends_on:
      - database
    image: n-app
    #volumes setting
    volumes:
      - "./app:/src"
    #Container name
    container_name: n-app
    #Port connection
    ports:                          
      - 3000:5000
    links:
      - redis
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mydatabase
      REDIS_URL: redis://cache
    tty: true
  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust