version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build:
      context: ./  
    depends_on:
      - database
    image: n-app
    #volumes setting
    volumes:
      - "./app:/src"
    #Container name
    container_name: n-app
    #Port connection
    ports:                          
      - 3000:5000
    links:
      - redis
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: petaway
      REDIS_URL: redis://cache
    tty: true
  database:
    image: postgres:12.3
    ports:
      - 5454:5454
    environment:
      POSTGRES_DB: petaway
      POSTGRES_HOST_AUTH_METHOD: trust
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - database
  
